services:
  - type: web
    name: verify-signature-service
    env: python
    runtime: python39  # Specifies the Python runtime environment
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -b 0.0.0.0:$PORT verify_signature:app  # Run the Flask app using Gunicorn
    envVars:
      - key: MONGO_URI
        value: "mongodb+srv://satvikvattipalli1311:8I4SOudfJO8n8fIp@signare.w1j4f.mongodb.net/?retryWrites=true&w=majority&appName=Signare"
      - key: BUCKET_NAME
        value: "signature_verification_storage"  # Google Cloud Storage bucket
      - key: SIMILARITY_THRESHOLD
        value: "0.8"  # Threshold for signature similarity
    plan: free  # Choose the pricing plan; switch to a paid plan for production
    autoDeploy: true  # Automatically deploy changes pushed to the repository
    healthCheckPath: /api/health-check  # Specifies the health check endpoint
    regions:
      - oregon  # Example: Choose a region closest to your users

    autoscaling:
      minInstances: 1
      maxInstances: 3  # Adjust max instances based on expected traffic

    static:
      - path: /static
        staticDir: static/  # Serve static files if required
